name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm help

      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
       
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Pull Image
        run: docker pull coherentsolutions/rest-training:2.0

      - name: Run 
        run: docker run -d -p 8050:8082 coherentsolutions/rest-training:2.0


      - name: Run tests
        run: mvn clean test 

      - name: Upload Extent HTML report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: go-rest-report
          path: reports/extent/report_*.html

