name: 'My Pipeline'
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  tests:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Pull Image
        run: docker pull coherentsolutions/rest-training:2.0
 
      - name: Run 
        run: docker run -d -p 8050:8082 coherentsolutions/rest-training:2.0
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
 
      - name: Run Test
        if: always()
        run: 
          mvn clean test
        continue-on-error: true
 
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
             test-results/**/*.xml
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results
 
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always() 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
